# Generated by Django 5.0.3 on 2026-09-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_joinrequest_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyinformation',
            name='gender',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
