# Generated by Django 5.0.3 on 2026-09-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_babyinformation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyinformation',
            name='gender',
            field=models.CharField(choices=[('1', '男性'), ('2', '女性')], default='1', max_length=2),
        ),
    ]
